theme: jekyll-theme-primer
title: Horizon Project
description: Instructional Design against Phishing
author:
  name: Eric Bréchemier
  github: eric-brechemier

exclude: ["assets", "portfolio", "research", "source", "templates"]
include: ["assets/miro-board/Needs-Analysis-Questions.csv"]
